#!/usr/bin/env bash
# Regenerates Modules/Sources/AppEnvironment/BuildValues+Generated.swift from environment
# variables. Run it in CI before building:
#
#   APP_ENVIRONMENT=prod API_BASE_URL_PROD=https://api.example.com scripts/generate-build-values.sh
#
#   APP_ENVIRONMENT       local | dev | prod (the build's default environment)
#   API_BASE_URL_DEV      optional, default http://localhost:8080. Plain http only for local hosts
#                         (localhost, *.local, unqualified names): that's all ATS allows, and only
#                         in Debug builds (Config/Debug-Info.plist). Anything else must be https.
#   API_BASE_URL_PROD     optional, empty = not configured (requests fail); must be https
#
# `local` always uses the in-app mock backend. Non-secret values only: the output is compiled
# into the app binary.
set -euo pipefail

: "${APP_ENVIRONMENT:?APP_ENVIRONMENT must be local, dev or prod}"
API_BASE_URL_DEV="${API_BASE_URL_DEV-http://localhost:8080}"
API_BASE_URL_PROD="${API_BASE_URL_PROD-}"

case "$APP_ENVIRONMENT" in
  prod) ALLOWS_OVERRIDE="false" ;;
  local|dev) ALLOWS_OVERRIDE="true" ;;
  *) echo "Invalid APP_ENVIRONMENT: $APP_ENVIRONMENT" >&2; exit 1 ;;
esac

URL_CHARS='[A-Za-z0-9.:/_-]+'
LOCAL_HTTP='^http://(localhost|[A-Za-z0-9-]+|[A-Za-z0-9.-]+\.local)(:[0-9]+)?(/[A-Za-z0-9./_-]*)?$'
if [[ -n "$API_BASE_URL_DEV" && ! "$API_BASE_URL_DEV" =~ ^https://$URL_CHARS$ && ! "$API_BASE_URL_DEV" =~ $LOCAL_HTTP ]]; then
  echo "Invalid API_BASE_URL_DEV (https, or http to a local host): $API_BASE_URL_DEV" >&2; exit 1
fi
if [[ -n "$API_BASE_URL_PROD" && ! "$API_BASE_URL_PROD" =~ ^https://$URL_CHARS$ ]]; then
  echo "Invalid API_BASE_URL_PROD (https only): $API_BASE_URL_PROD" >&2; exit 1
fi
if [[ "$APP_ENVIRONMENT" == "prod" && -z "$API_BASE_URL_PROD" ]]; then
  echo "APP_ENVIRONMENT=prod requires API_BASE_URL_PROD" >&2; exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/Modules/Sources/AppEnvironment/BuildValues+Generated.swift"

cat > "$OUT" <<EOF
import Foundation

// GENERATED by scripts/generate-build-values.sh. Do not edit or commit.
extension BuildValues {
    public static let current = BuildValues(
        defaultEnvironment: .$APP_ENVIRONMENT,
        configs: [
            .local: EnvironmentConfig(environment: .local, apiBackend: .mock),
            .dev: EnvironmentConfig(environment: .dev, apiBackend: .url("$API_BASE_URL_DEV")),
            .prod: EnvironmentConfig(environment: .prod, apiBackend: .url("$API_BASE_URL_PROD")),
        ],
        allowsOverride: isDebugBuild || $ALLOWS_OVERRIDE
    )
}
EOF

echo "Wrote $OUT ($APP_ENVIRONMENT)"
