#!/usr/bin/env bash
# Regenerates Modules/Sources/AppEnvironment/BuildValues+Generated.swift from environment
# variables. Run it in CI before building:
#
#   APP_ENVIRONMENT=prod API_BASE_URL_PROD=https://api.example.com \
#   API_BASE_URL_NONPROD=https://api.nonprod.example.com scripts/generate-build-values.sh
#
# Non-secret values only: the output is compiled into the app binary.
set -euo pipefail

: "${APP_ENVIRONMENT:?APP_ENVIRONMENT must be prod or nonProd}"
: "${API_BASE_URL_PROD:?}"
: "${API_BASE_URL_NONPROD:?}"

case "$APP_ENVIRONMENT" in
  prod) ALLOWS_OVERRIDE="false" ;;
  nonProd) ALLOWS_OVERRIDE="true" ;;
  *) echo "Invalid APP_ENVIRONMENT: $APP_ENVIRONMENT" >&2; exit 1 ;;
esac

for url in "$API_BASE_URL_PROD" "$API_BASE_URL_NONPROD"; do
  [[ "$url" =~ ^https://[A-Za-z0-9./_-]+$ ]] || { echo "Invalid URL: $url" >&2; exit 1; }
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/Modules/Sources/AppEnvironment/BuildValues+Generated.swift"

cat > "$OUT" <<EOF
import Foundation

// GENERATED by scripts/generate-build-values.sh. Do not edit or commit.
extension BuildValues {
    public static let current = BuildValues(
        defaultEnvironment: .$APP_ENVIRONMENT,
        configs: [
            .prod: EnvironmentConfig(environment: .prod, apiBaseURL: URL(string: "$API_BASE_URL_PROD")!),
            .nonProd: EnvironmentConfig(environment: .nonProd, apiBaseURL: URL(string: "$API_BASE_URL_NONPROD")!),
        ],
        allowsOverride: isDebugBuild || $ALLOWS_OVERRIDE
    )
}
EOF

echo "Wrote $OUT ($APP_ENVIRONMENT)"
